### ISSUE TITLE
Run archive

### ISSUE THREAD

**Issue by ArmandasRokas** [kpenov16/Runners#9]
Skal vi gemme produkter (RUN) eller opskrifter (ROUTE)?
- Hvis det er produkter, så skal vi gemme kopien af alle RUN med tilhørende opskrift (ROUTE). Det betyder, at RUN skal pege stadigvæk på den samme ROUTE. Kun det RUN_ARCHIVE, som blev arkiveret skal pege på gammel ROUTE_ARCHIVE. 
- Hvis det er opskrifter med tilhørende produkter, så skal vi gemme kopien af alle ROUTE. Men problemet er , at vi ikke kan ændre primary key for RUN til at pege på ROUTE_ARCHIVE, fordi hvis vi ændrer det så den vil pege på den gammel ROUTE, men det er ikke mening, fordi brugeren skal se den nyeste ROUTE, men ikke er ældre version af den. Det vil skabe inkonsistent, fordi hvis en bruger tilmelde sig til en RUN og den bliver ændret, men pege stadigvæk på en gammel ROUTE, så det betyder, at en bruger som tilmelde sig efter ændringer skal løbe en nye ROUTE, men en bruger, som tilmeld sig, før der blev ændret, skal løbe en gammel ROUTE. Dvs. bruger vil have forskellige informationer om ROUTE. Derfor vi kan ikke ændre nogen Primary keys i vores aktuelle tabler. 
- Hvis det er KUN opskrifter. Vi har kun ROUTE_ARCHIVE ikke nogen information om, hvilke RUN pegede på hvilke ROUTE tidligere. Men er det nok?

**Comment by ArmandasRokas** [comment]
My suggestion :
* On update on ROUTE
1. Make a copy of ROUTE and put that in ROUTE_ARCHIVE with the same id and timestamp
2. Select all runs in RUN with that route id, which has been updated. 
3. Make copy of these and put in RUN_ARCHIVE with foreign keys to route_id and timestamp in ROUTE_ARCHIVE 

* Goal with this solution that we  can check which runs was associated with older version of route. 

This suggestion not includes WAYPOINTS for simplicity.

**Comment by kpenov16** [comment]
Jeg fik lavet en lille eksperiment kun for route og det virker fint (jeg synes det er nemmere bare at eksperimentere lidt og se hvad der sker):

Jeg tror du prøver at løse alt for mange ting på en gang. 
Jeg deler dem op i små bid så det er nemmere at spise :) 

CREATE TABLE route(
	id INT NOT NULL,
    description VARCHAR(225),
    distance VARCHAR(225),
    PRIMARY KEY (id)
);

INSERT INTO route (id, description, distance) VALUES (1, 'fast run', '5 km');
INSERT INTO route (id, description, distance) VALUES (2, 'slow run', '15 km');
INSERT INTO route (id, description, distance) VALUES (3, 'moderate run', '70 km');
SELECT * FROM route;

UPDATE route
SET distance = '7 km'
WHERE id = 3;

SELECT * FROM route_archive;

CREATE TABLE waypoint(
	id INT NOT NULL,
	route_id INT NOT NULL,
    point_index INT NOT NULL,
    coordinate VARCHAR(225),
    PRIMARY KEY (id, route_id, point_index),
    FOREIGN KEY (route_id) REFERENCES route (id)
); 

INSERT INTO waypoint (id, route_id, point_index, coordinate) VALUES (1, 1, 1, '5,5');
INSERT INTO waypoint (id, route_id, point_index, coordinate) VALUES (2, 1, 2, '10,10');

INSERT INTO waypoint (id, route_id, point_index, coordinate) VALUES (3, 2, 1, '5,5');
INSERT INTO waypoint (id, route_id, point_index, coordinate) VALUES (4, 2, 2, '7,7');
INSERT INTO waypoint (id, route_id, point_index, coordinate) VALUES (5, 2, 3, '10,10');

INSERT INTO waypoint (id, route_id, point_index, coordinate) VALUES (6, 3, 1, '10,10');
INSERT INTO waypoint (id, route_id, point_index, coordinate) VALUES (7, 3, 2, '20,20');

SELECT * FROM waypoint;

DELIMITER //
CREATE TRIGGER AfterUpdateOnRoute
AFTER UPDATE ON route
FOR EACH ROW
BEGIN
	INSERT INTO route_archive (id, description, distance, updated)
    VALUES (OLD.id, OLD.description, OLD.distance, CURRENT_TIMESTAMP());
END//
DELIMITER ;

CREATE TABLE route_archive(
	id INT,
    description VARCHAR(225),
    distance VARCHAR(225),
    updated TIMESTAMP NOT NULL
);

CREATE TABLE waypoint_archive(
	id INT,
	route_id INT,
    point_index INT,
    coordinate VARCHAR(225),
    updated TIMESTAMP NOT NULL
);

**Comment by ArmandasRokas** [comment]
> Jeg tror du prøver at løse alt for mange ting på en gang.
> Jeg deler dem op i små bid så det er nemmere at spise :)

Helt enig! Og jeg synes, at din løsning er nok til vores Database projekt, fordi det er vigtigeste at vi viser vores forståelse og anvendelse af Triggers.
Men  vi kan selvføgelig evt. tilfløje flere triggers til sidst, hvis vi har overskud og vi færdig med alt andet :)

**Comment by ArmandasRokas** [comment]
Hej Kaloyan! 
Jeg fik arbejdet lidt videre på din SQL script. Jeg har tilføjet at der indsættes alle waypoints til archive, som tilhører vedrørende route:) Så vi har styr på hvilke waypoint tilhørte hvilke version af route. 
Vi mangler bare lave det samme hvis der updates på en waypoint, tilføjes flere eller slettes waypoint, så skal vi gemme hele lortet igen :) 

OBS: jeg har tilføjet foreign keys to waypoint_archive og primary keys til route_archive

https://github.com/kpenov16/Runners/blob/master/docs/sql/route_trigger_updated_with_archiving_waypoints.sql

**Comment by kpenov16** [comment]
Hej Armandas :) 
Det ser ud som om at det vil være nemmere at vi først implementerer CRUD med automatiseret test på vores databese design som det er nu og bagefter tænke på hvordan vi arkiverer. Det er nemlig afgørende hvodan vi implementer CRUD for hvordan vi arkiverer. Jeg tror vi mangler en "stored procedure" når vi laver update og delete på route og waypoint, altså route og waypoint som unit of work.
